/********************************************************************
**       This cc file is generated by program,                     **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pytimer.pkg

#include "pytimer.pybind11.h"


#include "pytimer.h"


#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <algorithm>

PYBIND11_MODULE(pytimer, m) {

    pybind11::class_<CPytimer, CDMTimerNode>(m, "CPytimer")
    .def("settimer", &CPytimer::settimer, pybind11::return_value_policy::automatic_reference)
    .def("killtimer", &CPytimer::killtimer, pybind11::return_value_policy::automatic_reference)
    .def("killall", &CPytimer::killall, pybind11::return_value_policy::automatic_reference)
    .def("sleepms", &CPytimer::sleepms, pybind11::return_value_policy::automatic_reference)
    .def("stop", &CPytimer::stop, pybind11::return_value_policy::automatic_reference)
    .def("run", &CPytimer::run, pybind11::return_value_policy::automatic_reference)
    .def("poll", &CPytimer::poll, pybind11::return_value_policy::automatic_reference)
    .def("gettime", &CPytimer::gettime, pybind11::return_value_policy::automatic_reference);

}
