/********************************************************************
**       This cc file is generated by program,                     **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pytimer.pkg

#include "pytimer.pybind11.h"


#include "dmtimersink.h"

#include "dmtimernode.h"

#include "pytimer.h"


#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <algorithm>

PYBIND11_MODULE(pytimer, m) {

    pybind11::class_<ITimerSink>(m, "ITimerSink");

    pybind11::class_<CDMTimerElement>(m, "CDMTimerElement");

    pybind11::class_<CDMTimerNode, ITimerSink>(m, "CDMTimerNode");

    m.def("stop", &stop, pybind11::return_value_policy::automatic_reference);
    m.def("run", &run, pybind11::return_value_policy::automatic_reference);
    m.def("poll", &poll, pybind11::return_value_policy::automatic_reference);
    m.def("gettime", &gettime, pybind11::return_value_policy::automatic_reference);
    pybind11::class_<CPyTimer, CDMTimerNode, ITimerSink>(m, "CPyTimer")
    .def(pybind11::init<>())
    .def("settimer", &CPyTimer::settimer, pybind11::return_value_policy::automatic_reference)
    .def("killtimer", &CPyTimer::killtimer, pybind11::return_value_policy::automatic_reference)
    .def("killall", &CPyTimer::killall, pybind11::return_value_policy::automatic_reference)
    .def("sleepms", &CPyTimer::sleepms, pybind11::return_value_policy::automatic_reference);

}
