/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pytimer.pkg

#ifndef __PYTIMER_PYBIND11_H__
#define __PYTIMER_PYBIND11_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif  // __PYTIMER_PYBIND11_H__
